config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'donate/index'

  get 'subscriptions/index'

  get 'subscriptions/plans'

  get 'subscriptions/stripe_checkout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  match 'users/show/:id', to: 'users#show', via: 'get', as: 'users_show'
  match '/stripe_checkout' => 'subscriptions#stripe_checkout' , via: 'post'
  match '/pay_with_paypal' => 'subscriptions#pay_with_paypal' , via: 'post'
  resources :feeds do
    resources :comments
  end
  resources :feeds do
    member do
      put "like" => "feeds#upvote"
      put "unlike" => "feeds#downvote"
      put "unvote" => "feeds#unvote"
    end
  end

  resources :conversations do
    resources :messages, only: [:create]
  end

  resources :notifications

  post 'pusher/auth'
  root 'feeds#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	
  validates :text, presence: true,length: { within: 1..200 }
  belongs_to :user
  acts_as_votable

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	# http_basic_authenticate_with name: "root", password: "passpass", except: [:index, :show]
	# before_action :authenticate_user! , except: [:index, :show]
	load_and_authorize_resource except: [:create, :index]

	def new
		@feed = current_user.feeds.build
	end

	def index
		@feeds = Feed.all
		@feed = Feed.new
		respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
		end
	end

	def create
		@feed = current_user.feeds.build(feed_params)
		@feed.name = current_user.username
		respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.js
      else
        format.html { render action: "index" }
        format.js
      end
    end
	end

	def edit
		@feed = Feed.find(params[:id])
	end

	def update
		@feed = Feed.find(params[:id])
		respond_to do |format|
			if @feed.update(feed_params)
	      format.html { redirect_to feeds_path }
	      format.js
			else
				format.html { render :edit }
	      format.js
			end
		end
	end

	def show
		@feed = Feed.find(params[:id])
	end

	def destroy
		@feed = Feed.find(params[:id])
		@feed.destroy
		respond_to do |format|
      format.html { redirect_to feeds_url,notice: 'Feed was successfully deleted.' }
      format.js
    end
	end

	def upvote
		@feed = Feed.find(params[:id])
		@feed.upvote_by current_user
		respond_to do |format|
			if @feed.upvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def unvote
		@feed = Feed.find(params[:id])
		@feed.unvote_by current_user
		respond_to do |format|
			if @feed.unvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	def downvote
		@feed = Feed.find(params[:id])
		@feed.downvote_by current_user
		respond_to do |format|
			if @feed.downvote_by current_user
				format.html { redirect_to :back }
				format.js
			end
		end
	end

	
	private
	def feed_params
		params.require(:feed).permit(:name,:text)
	end

end

app/helpers/feeds_helper.rb
module FeedsHelper
	
end

app/views/feeds/_feed.html.erb
<div class="col-md-6 blog-main box">
    <div class="bs-component">
    <div class="alert alert-dismissible boxbackgroundcolor" id="feed<%= feed.id%>">
      <% if feed.user.avatar.url %>
        <%= link_to image_tag(feed.user.avatar.url(:thumbnail), :class=> "img-thumbnail", size: "40"), users_show_path(feed.user_id) , title: feed.user.username %>
        <strong><%= link_to feed.user.username , users_show_path(feed.user_id) %> </strong>
      <% else %>
          <strong><%= link_to feed.user.username , users_show_path(feed.user_id) %> </strong>
      <% end %> :
      <%= link_to feed.text, feed %>
      <time datetime="<%= feed.updated_at %>" title="<%= feed.updated_at.strftime("%d %b  %Y at %I:%M%p") %>">
        <h6><%= time_ago_in_words(feed.updated_at)+" ago."%> </h6>
      </time>
      <hr class="margin5">
      <%= render partial: "votes", locals: {feed: feed} %>
      <span class="pull-right" >
      <% if user_signed_in? %>
          <% if can? :update, feed %>
                <button type="button" class="btn btn-xs" data-toggle="modal" data-target="#myupdatefeed_<%=feed.id%>"><i class="fa fa-pencil-square-o">Edit</i></button>
          <% end %>
          <% if can? :destroy, feed %>
                <%= link_to feed, method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
                    <i class="fa fa-lg fa-trash-o"></i>
                <% end %>
          <% end %>
      <% end %>
      </span>
      <%= render partial: "comments/quickcomment", locals: {feed: feed} %>
    </div>
  </div>
</div>

<%= form_for(feed, :method => :put, remote: true) do |f| %>
    <div class="modal fade" id="myupdatefeed_<%= feed.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Edit</h4>
          </div>
          <div class="modal-body">

            <div class="field">
              <%= f.label :Feed %>
              <%= f.text_area :text, class: "form-control"%>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" id="mynewpostclose">Close</button>
            <%= submit_tag "Update", class: "btn btn-primary" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/feeds/_form.html.erb
<%= form_for @feed, remote: true, :html => {:required => true} do |f| %>
 
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@feed.errors.count, "error") %> prohibited
        this feed from being saved:
      </h2>
      <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.text_area :text,:class=> "form-control feed_content",:placeholder=> "Keep within 1 to 200 letters !", :required => "required",:maxlength=>"200" %>
  </p>
  <p>
    <%= f.submit " Feed It !", class: "btn btn-primary btn-sm pull-right"%>
  </p>
<% end %>

app/views/feeds/_votes.html.erb
<%= link_to pluralize(feed.comments.count, 'comment'), feed, class: "btn btn-xs"  %>
<% if user_signed_in? %>
    <% if current_user.voted_up_for? feed  %>
        <%= link_to unvote_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_upvotes.size %>
            <i class="fa fa-thumbs-up fa-lg"></i>
        <% end %>
    <% else %>
        <%= link_to like_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_upvotes.size %>
            <i class="fa fa-thumbs-o-up fa-lg"></i>
        <% end %>
    <% end %>
    <% if current_user.voted_down_for? feed  %>
        <%= link_to unvote_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_downvotes.size %>
            <i class="fa fa-thumbs-down fa-lg"></i>
        <% end %>
    <% else %>
        <%= link_to unlike_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
            <%= feed.get_downvotes.size %>
            <i class="fa fa-thumbs-o-down fa-lg"></i>
        <% end %>
    <% end %>
<% else %>
    <%= link_to like_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
        <%= feed.get_upvotes.size %>
        <i class="fa fa-thumbs-o-up fa-lg"></i>
    <% end %>
    <%= link_to unlike_feed_path(feed), method: :put,remote: true, class: "btn btn-xs" do %>
        <%= feed.get_downvotes.size %>
        <i class="fa fa-thumbs-o-down fa-lg"></i>
    <% end %>
<% end %>

app/views/feeds/create.js.erb
$(".feed_content").val('');
$("#container_feeds").prepend('<%= j render @feed  %>');

app/views/feeds/destroy.js.erb
$("#feed<%= @feed.id%>").remove();

app/views/feeds/downvote.js.erb
$("#feed<%= @feed.id%>").remove();
$("#container_feeds").prepend('<%= j render @feed  %>');

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form'%>
 
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <% if user_signed_in? %>
              <%= render 'form'%>
          <% else %>
              <p>Sign In Please ! </p>
              <%= render 'devise/sessions/form' %>
          <% end %>
        </div>
      </div>
    </div>
</div>

<div class="row" id="container_feeds">
    <%= render @feeds.reverse %>
</div>

app/views/feeds/new.html.erb
<h1>Post New Feed</h1>
<%=  render 'form' %>
<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<div class="col-md-6">
    <div>
      <%= link_to :back do  %>
          <i class="fa fa-long-arrow-left fa-2x"></i>
      <% end %>
    </div>
  <br>
  <div class="bs-component">
    <div class="alert alert-dismissible boxbackgroundcolor">
    <p>
      <%= image_tag(@feed.user.avatar.url, :class=> "img-circle", size: "60") %>
    </p>
    <p>
      <%= link_to @feed.user.username, users_show_path(@feed.user_id) %>
    </p>


    <p>
      <i class="fa fa-quote-left fa-fw"></i>
      <%= @feed.text %>
      <i class="fa fa-quote-right fa-fw"></i>
    </p>

    <h5>
      Created
      <%= time_ago_in_words(@feed.created_at)+" ago" %>
    </h5>

    <h6>
      Last Updated
      <%= time_ago_in_words(@feed.updated_at)+" ago" %>
    </h6>


      <hr class="margin5">

    <% if user_signed_in? %>
        <% if current_user.voted_up_for? @feed %>
            <%= link_to unvote_feed_path(@feed ), method: :put, class: "btn btn-success btn-xs" do %>
                <%= @feed.get_upvotes.size %>
                <i class="fa fa-thumbs-up fa-lg"></i>
            <% end %>
        <% else %>
            <%= link_to like_feed_path(@feed ), method: :put, class: "btn btn-success btn-xs" do %>
                <%= @feed.get_upvotes.size %>
                <i class="fa fa-thumbs-o-up fa-lg"></i>
            <% end %>
        <% end %>
        <% if current_user.voted_down_for? @feed   %>
            <%= link_to unvote_feed_path(@feed ), method: :put, class: "btn btn-warning btn-xs" do %>
                <%= @feed.get_downvotes.size %>
                <i class="fa fa-thumbs-down fa-lg"></i>
            <% end %>
        <% else %>
            <%= link_to unlike_feed_path(@feed ), method: :put, class: "btn btn-warning btn-xs" do %>
                <%= @feed.get_downvotes.size %>
                <i class="fa fa-thumbs-o-down fa-lg"></i>
            <% end %>
        <% end %>
    <% else %>
        <%= link_to like_feed_path(@feed), method: :put, class: "btn btn-success btn-xs" do %>
            <%= @feed.get_upvotes.size %>
            <i class="fa fa-thumbs-o-up fa-lg"></i>
        <% end %>
        <%= link_to unlike_feed_path(@feed), method: :put, class: "btn btn-warning btn-xs" do %>
            <%= @feed.get_downvotes.size %>
            <i class="fa fa-thumbs-o-down fa-lg"></i>
        <% end %>
    <% end %>
      <span class="pull-right">
          <% if user_signed_in? %>
              <% if can? :update, @feed %>
                  <button type="button" class="btn btn-xs" data-toggle="modal" data-target="#myupdatefeed_<%= @feed.id%>"><i class="fa fa-pencil-square-o">Edit</i></button>
                  <% end %>
                  <% if can? :destroy, @feed %>
                      <%= link_to @feed, method: :delete, data: {confirm: "Are you sure?"} do %>
                      <i class="fa fa-lg fa-trash-o"></i>
                  <% end %>
              <% end %>
          <% end %>
      </span>

    <% if @feed.get_downvotes.voters.any? %>
        <h6>Unliked By: <% @feed.get_downvotes.voters.reverse.each do |p| %><%= link_to(p.username, users_show_path(p.id)) %> <% end %></h6>
    <% end %>

    <% if @feed.get_upvotes.voters.any? %>
        <h6>Liked By: <% @feed.get_upvotes.voters.reverse.each do |p| %><%= link_to(p.username, users_show_path(p.id) ) %> <% end %></h6>
    <% end%>

    </div>
  </div>
    <p>Comments:</p>
    <div id="comment_container">
        <% if @feed.comments.any? %>
                <%= render @feed.comments.reverse %>
        <% else %>
            <p id="no-comment">No Comments on this Feed, Be the first one !</p>
        <% end %>
    </div>


</div>
<div class="col-md-6">
  <br>
  <br>
  <div class="fixed-element-right">
      <div class="bs-component">
        <div class="alert alert-dismissible boxbackgroundcolor">
        <% if user_signed_in? %>
            <%= render 'comments/form' %>
        <% else %>
            <p>To Post Comment, Please Sign In !
            <%= render 'devise/sessions/form' %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %>
            </p>
              <p>
                <%= link_to "Sign Up", new_user_registration_path %>
            </p>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/feeds/unvote.js.erb
$("#feed<%= @feed.id%>").remove();
$("#container_feeds").prepend('<%= j render @feed  %>');
$(".col-md-6 blog-main box").remove();

app/views/feeds/upvote.js.erb
$("#feed<%= @feed.id%>").remove();
$()
$("#container_feeds").prepend('<%= j render @feed  %>');
$(".col-md-6 blog-main box").remove();