config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'donate/index'

  get 'subscriptions/index'

  get 'subscriptions/plans'

  get 'subscriptions/stripe_checkout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  match 'users/show/:id', to: 'users#show', via: 'get', as: 'users_show'
  match '/stripe_checkout' => 'subscriptions#stripe_checkout' , via: 'post'
  match '/pay_with_paypal' => 'subscriptions#pay_with_paypal' , via: 'post'
  resources :feeds do
    resources :comments
  end
  resources :feeds do
    member do
      put "like" => "feeds#upvote"
      put "unlike" => "feeds#downvote"
      put "unvote" => "feeds#unvote"
    end
  end

  resources :conversations do
    resources :messages, only: [:create]
  end

  resources :notifications

  post 'pusher/auth'
  root 'feeds#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates :first_name, presence: true,
                    length: { minimum: 2 }
  validates :username, presence: true,
                    length: { minimum: 2 }, uniqueness: { case_sensitive: false }
  # validates :avatar, presence: true
  # validates :time_zone, presence: true

  has_many :feeds, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :messages, dependent: :destroy
  acts_as_voter

  def clear_conversation_notifications(conversation_id)
    notifications.where(conversation_id: conversation_id).each do |n|
      n.update_attributes(read: true)
    end
  end

  def new_notification
    notifications.where(read: false).count
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/views/users/show.html.erb
<div class="col-md-4">
  <div>
    <%= link_to :back do  %>
        <i class="fa fa-long-arrow-left fa-2x"></i>
    <% end %>
  </div>
  <br>
  <div class="alert boxbackgroundcolor" role="alert">
    <%= image_tag(@user.avatar.url, :class=> "img-thumbnail", size: "200") if @user.avatar.url %>
      <% if @user.admin == true %>
          <h6>Admin</h6>
      <% else %>
          <h6>Normal User</h6>
      <% end %>
      <h2>
      <%= @user.first_name %>
      <%= @user.last_name %>
    </h2>
    <% if current_user && current_user != @user %>
        <%= link_to "Send Message", conversations_path(:sender_id => current_user.id , :recipient_id => @user.id ), :method => :post, class: "btn btn-success btn-xs start-conversation" %>
    <% end %>
    <h6><%= "Member Since "+(@user.created_at.to_formatted_s(:long_ordinal))%></h6>
    <% unless @user.about_me %>
        <p>
                <%= simple_format(@user.about_me) %>
        </p>
    <% end %>
    </div>

</div>
<div class="col-md-4" id="container_feeds">
	<h3>Feeds By <%= @user.username.capitalize %></h3>
  <% if @user.feeds.any? %>
      <% @user.feeds.reverse.each do |f| %>
            <div class="bs-component">
              <div class="alert alert-dismissible boxbackgroundcolor" id="feed<%= f.id%>">
                <button class="close" data-dismiss="alert" type="button">×</button>
                <i class="fa fa-quote-left fa-fw"></i><%= link_to f.text, f %><i class="fa fa-quote-right fa-fw"></i>
                <h6><%= time_ago_in_words(f.updated_at)+" ago."%> </h6>
                <hr class="margin5">
                <%= render partial: "feeds/votes", locals: {feed: f} %>
                <% if user_signed_in? %>
                    <% if can? :update, f %>
                        <button type="button" class="btn btn-xs" data-toggle="modal" data-target="#myupdatefeed_<%=f.id%>"><i class="fa fa-pencil-square-o">Edit</i></button>
                    <% end %>
                    <% if can? :destroy, f %>
                        <%= link_to f, method: :delete, remote: true, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-lg fa-trash-o"></i>
                        <% end %>
                    <% end %>
                <% end %>
              </div>
            </div>
      <% end %>
  <%else %>
    <p>None</p>
  <% end %>

</div>
<div class="col-md-4">
	<h3>Comments By <%= @user.username.capitalize %></h3>
	<% if @user.comments.any? %>
      <% @user.comments.reverse.each do |c| %>
            <div class="bs-component">
              <div class="alert alert-dismissible boxbackgroundcolor" id="comment<%= c.id%>">
                <button class="close" data-dismiss="alert" type="button">×</button>
                <h4>"<%=link_to c.body, Feed.find(c.feed_id) %>"</h4>
                  <i class="fa fa-angle-double-right"> <%= link_to Feed.find(c.feed_id).user.username.capitalize, users_show_path(Feed.find(c.feed_id).user_id) %> :
                    "<%= link_to Feed.find(c.feed_id).text, Feed.find(c.feed_id)%>"</i>
                  <h6><%= time_ago_in_words(c.updated_at)+" ago."%> </h6>
              </div>
            </div>
      <% end %>
    <% else %>
        <p>None</p>
    <% end %>

</div>

app/views/users/unvote.js.erb
$("#feed<%= @feed.id%>").remove();
$("#container_feeds").prepend('<%= j render @feed  %>');

app/views/users/update.js.erb
$("#feed<%= @feed.id%>").remove();
$("#myupdatefeed_<%= @feed.id %>").modal('hide');
$(".modal-backdrop").remove();
$("#container_feeds").prepend('<%= j render @feed %>');

app/views/users/upvote.js.erb
$("#feed<%= @feed.id%>").remove();
$()
$("#container_feeds").prepend('<%= j render @feed  %>');