config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'donate/index'

  get 'subscriptions/index'

  get 'subscriptions/plans'

  get 'subscriptions/stripe_checkout'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  match 'users/show/:id', to: 'users#show', via: 'get', as: 'users_show'
  match '/stripe_checkout' => 'subscriptions#stripe_checkout' , via: 'post'
  match '/pay_with_paypal' => 'subscriptions#pay_with_paypal' , via: 'post'
  resources :feeds do
    resources :comments
  end
  resources :feeds do
    member do
      put "like" => "feeds#upvote"
      put "unlike" => "feeds#downvote"
      put "unvote" => "feeds#unvote"
    end
  end

  resources :conversations do
    resources :messages, only: [:create]
  end

  resources :notifications

  post 'pusher/auth'
  root 'feeds#index'

end

app/views/layouts/_footer.html.erb
<div>
  <hr class="margin5">
    A Sample Blog Built On Rails
    by <%= link_to "Nirajan Raj Pokharel", users_show_path(1) %>
    <div class="pull-right">
      <%= link_to "Donate !", donate_index_path %>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feed It !</title>
  <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://js.pusher.com/3.0/pusher.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'/>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="fa fa-bolt fa-lg">
            Feed It</i> </a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><%# image_tag(current_user.avatar.url, :class=> "img-circle", :size => "50") %></li>
                <li><%= link_to current_user.first_name+" "+current_user.last_name, edit_user_registration_path, :title => "Edit Profile" %></li>
                <% if current_user.admin == true %>
                    <li><%= link_to "Manage Blog", rails_admin.dashboard_path %></li>
                <% end %>
                <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete%></li>
                <li class="dropdown dropdown_<%=current_user.id%>">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="badge badge_bob_<%= current_user.id %>"><%= current_user.new_notification %></span> <span class= "notification_bob_<%=current_user.id%>">Notifications <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <% if current_user.notifications %>
                        <% current_user.notifications.reverse[0...5].each do |n| %>
                            <li class=<%= n.read == true ? '' : "alert-success"%>><%= link_to "#{n.sender.username} sent you a new message" , n.conversation%></li>
                        <% end %>
                    <% end %>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Show All", notifications_index_path %></li>
                  </ul>
                </li>
          <% else %>
                <li><%= link_to "Sign up", new_user_registration_path%></li>
                <li><%= link_to "Sign In", new_user_session_path%></li>

            <% end %>
            <li><%= link_to "Donate !", donate_index_path %></li>
          </ul>
      </div>
    </div>
  </nav>




  <div class="container">
      <br>
      <br>
      <br>
      <br>
    <% if notice %>
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= notice %>
          </div>
    <% end %>
    <% if alert %>
          <div class="alert alert-warning alert-dismissible alert-bottom" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= alert %>
          </div>
    <% end %>

    <%= yield %>

  </div>
  <div class="container">
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

<script>
  <% if current_user %>
    console.log("from application");
    PNotify.desktop.permission();
    var pusher = new Pusher('<%= Pusher.key %>', {
        encrypted: true
    });

    pusher.connection.bind('connected', function () {
        var socket_id = pusher.connection.socket_id;
        $('#socket_id').val(socket_id);
    });

    var channel = pusher.subscribe("private-notification<%= current_user.id.to_s %>");
    channel.bind('my_notification', function(data) {
        console.log("from application subscriber");
        var sender_id = data.sender_id
        var sender = data.sender
        var reciever_id = $('meta[name=user-id]').attr("content");
        var conversation_url = "conversations/" + data.conversation_id
        var message = data.message

        if ( (sender_id != reciever_id) && window.location.pathname !=  '/'+conversation_url ) {

          (new PNotify({
              title: 'New Message',
              text: sender + ' said\: ' + message,
              desktop: {
                desktop: true
              }
          })).get().click(function(e) {
              if ($('.ui-pnotify-closer, .ui-pnotify-sticker, .ui-pnotify-closer *, .ui-pnotify-sticker *').is(e.target)) return;
              window.location.href = conversation_url;
          });

          var isOldTitle = true;
          var oldTitle = "Feed It ! ";
          var newTitle = sender + " says "  + message;
          var interval = null;
          function changeTitle() {
              document.title = isOldTitle ? oldTitle : newTitle;
              isOldTitle = !isOldTitle;
          }
          interval = setInterval(changeTitle, 700);

          $(window).focus(function () {
              clearInterval(interval);
              $("title").text(oldTitle);
          });

          var badge = $('.badge_bob_<%=current_user.id%>');
          badge.text('+1 New');
          $('.dropdown_<%=current_user.id%> > ul').prepend("<li><a href=/"+conversation_url+">New message from " + sender + "</a></li>");
          var new_notice = $('.dropdown_<%=current_user.id%> > ul > li').first();
          new_notice.find('a').toggleClass("alert alert-warning");
        }
    });
  <% end %>
</script>